version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - node ace migration:run
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
env:
  variables:
    PORT: '{{resolve:ssm:/tmi/PORT:1}}'
    HOST: '{{resolve:ssm:/tmi/HOST:1}}'
    APP_KEY: '{{resolve:ssm:/tmi/APP_KEY:1}}'
    DRIVE_DISK: '{{resolve:ssm:/tmi/DRIVE_DISK:1}}'
    PG_HOST: '{{resolve:ssm:/tmi/PG_HOST:1}}'
    PG_USER: '{{resolve:ssm:/tmi/PG_USER:1}}'
    PG_DB_NAME: '{{resolve:ssm:/tmi/PG_DB_NAME:1}}'
    NODE_ENV: 'development'
    DB_CONNECTION: 'pg'
    PG_PASSWORD: '{{resolve:ssm:/tmi/PG_PASSWORD:1}}'
    PG_PORT: '{{resolve:ssm:/tmi/PG_PORT:1}}'
    SESSION_DRIVER: 'cookie'
