version: 0.2
parameter-store:
  HOST: '/tmi/HOST'
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - node ace migration:run
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
env:
  variables:
    PORT: '{{resolve:ssm:/tmi/PORT}}'
    HOST: echo $HOST
    APP_KEY: '{{resolve:ssm:/tmi/APP_KEY}}'
    DRIVE_DISK: '{{resolve:ssm:/tmi/DRIVE_DISK}}'
    PG_HOST: '{{resolve:ssm:/tmi/PG_HOST}}'
    PG_USER: '{{resolve:ssm:/tmi/PG_USER}}'
    PG_DB_NAME: '{{resolve:ssm:/tmi/PG_DB_NAME}}'
    NODE_ENV: 'development'
    DB_CONNECTION: 'pg'
    PG_PASSWORD: '{{resolve:ssm:/tmi/PG_PASSWORD}}'
    PG_PORT: '{{resolve:ssm:/tmi/PG_PORT}}'
    SESSION_DRIVER: 'cookie'
