version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - node ace migration:run
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
